### ISSUE TITLE
HTML dir attribute 

### ISSUE THREAD

**Issue by omar-imran** [tysonmatanich/directional-scss#4]
How can **_directional-scss_** detect HTML dir attribute value? or, how can we pass HTML dir attribute value to **_scss_** file?

maybe:

@if(html[dir]=="rtl") {$dir: rtl;}
@else {$dir: ltr;}

**Comment by tysonmatanich** [comment]
Scss is compiled into CSS on the server so you therefore cannot detect client-side HTML attributes at that time. However, you should know what document direction a given page uses and can then include the appropriate CSS bundle. You should organize your project to create separate LTR and RTL bundles. For example `site-ltr.css` and `site-rtl.css`. I updated the readme file to explain this further.

Also, I just updated the CodePen demos as they broke at some point.
