### ISSUE TITLE
Dynamically changing pseudo elements (i.e. before -> after)

### ISSUE THREAD

**Issue by mcfoton** [tysonmatanich/directional-scss#5]
Hi!
Is there a way to change 'before' pseudo element to 'after'?  Currently syntax like
```
icon:#{if-ltr('before', 'after')} {
      ...
}
```
produces syntax error

Thank you so much for this awesome .scss!

**Comment by tysonmatanich** [comment]
Your example is correct and works fine for me (https://codepen.io/tysonmatanich/pen/XEQrMJ). Perhaps there is an error somewhere else in your scss file.

**Comment by mcfoton** [comment]
Totally, thanks! The issue was other place and the pseudo class changes appropriately.
Just a syntax error from IntelliJ you can ignore
![Image of error](https://monosnap.com/image/ZfUJzg2CDTfRyvDSQlxVmRckskAyCz.png)
